# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: checkout repository 
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: ls -la
    - run: pwd
    - name: Build with Maven product catatlogue
      run: mvn -B package --file productcatalogue/pom.xml
      
    - name: Build with Maven Stockmanager
      run: mvn -B package --file stockmanager/pom.xml

    - name: Build with Maven shopfront
      run: mvn -B package --file shopfront/pom.xml
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build docker image product
      run: docker build -t nouramine/product productcatalogue/
      
    - name: Build docker image shopfront
      run: docker build -t nouramine/shop shopfront/
      
    - name: Build docker image stockmanager
      run: docker build -t nouramine/stock stockmanager/

    - name: affichage docker images
      run: docker image ls

    - name: Push docker image shopfront
      run: docker push nouramine/shop

    - name: Push docker image productcatalogue
      run: docker push nouramine/product

    - name: Push docker image stockmanager
      run: docker push nouramine/stock
  
      
    
      
   
